# Introduction to Python and Jupyter Notebook

(Acknowledgement: this tutorial is adapted from a tutorial notebook developed for AM201 at Harvard University)

This tutorial will introduce relevant python packages for this course and the web-based interactive python environment: Jupyter notebook. Coding examples will be given. Hope you find it helpful and like it!

This tutorial is hopefully suitable for beginners. If you are new to programming and find difficulties in understanding the two major examples at the end, please don't hesitate to let me know. I'll be glad to help you get on track quickly.

## I. Jupyter notebook

Jupyter Notebook (Formerly IPython Notebooks) is a web-based interactive computational environment for creating Jupyter notebooks documents.

<div class="alert alert-block alert-info">
<b>Tip:</b> Cell has two major interchangeable types: <b> Code </b> and <b> Markdown </b> (excellent text editor)
</div>

<div class="alert alert-block alert-info">
<b>Tip:</b> Double-click every Markdown cells in this tutorial to see features.
</div>

### Markdown cells

Before playing with python in these notebooks, I'd like to first introduce a huge convenience of Jupyter notebook which is it features Markdown cells, which is a text editor with various styles of text supported.

**This** notebook itself is a Jupyter notebook. You can either save this file as *.ipynb file to your local computer and open with your own Jupyter notebook reader, or save this file to your google drive and use Google Colab to play with it.

Then start playing!

#### Basic features

1. When you hit `esc`, then hit `m`, you turn the cell from code into Markdown. hit `esc` then `y` brings the cell back to codes.


2. After typing, you should also hit `shift+return/enter` to turn Markdown cell into display. Also hit `shift+return/enter` to run codes


3. When you hit `esc` then `1`, it gives you the 1st order title. Esc+2 is the 2nd order title and so on. Equivalently, after turning a cell into Markdown, you can type $n$ "#" and type your $n$th title after it.


4. Enumeration is automatically styled. You'll see the text of an enumeration is blue before you hit shift+return.


5. Compatible to latex style equations for both "inline" style and "display" style of latex. Example: $e^{i\pi}+1=0$ $$e^{i\pi}+1=0$$


6. <b> Bold </b> and <i>Italic</i>


7. To create a new cell, click "+" in the toolbar or hit `esc` then `b`


8. To delete a cell, the quickest way is `esc` then `x`. This is cut option. You can use `esc` then `v` to paste it somewhere else


9. For faster operation, hit `command (control)+shift+p` or click the keyboard icon in the toolbar to see shortcuts. (hitting esc enters the command mode)

Automatic styling of enumeration:

- Bullet 1
    - Bullet 2
        - Bullet 3

1. Point 1
    1. Point 1.1
        1. Point 1.1.1

<u> Summary of shortcuts </u>

- `esc` + `b`: Create new cell below
- `esc` + `m`: Change cell to Markdown
- `esc` + `y`: Change cell to Code
- `esc` + `dd`: Delete cell (The description in the command palette is amazingly misleading..)
- `esc` + `z`: Undo cell deletion
- `esc` + `x`: Cut cell
- `esc` + `v`: Paste cell
- `shift` + `return`: Run a cell
- `esc` + `ii`: Kill a running cell (To complecated, or infinite loop)
- `esc` + `f`: Find and replace
- `esc` + `1-4`: Creating titles level 1 to 5
- ...

#### Code illustration

Double-click cell below to see code. It can be easily turn into runable codes by changing the cell type to Code and delete the first and the last line.


print("Hello World")



# Title 1
## Title 2
### Title 3
#### Title 4
##### Title 5

### Doing python in Jupyter notebooks

If you are a Mathematica user you are automatically familiar with jupyter notebooks. Just type as many lines of python codes in a cell as you like and hit `shift+enter/return`. In short, Jupyter notebooks

1. Evaluate individual cell at a time
2. Considers every cell evaluated previously when evaluating a new cell

In [ ]:
a=1.3 # don't have to declare
a+5

6.3

If one of your code sentence is longer than a line, use `\`

In [ ]:
1+
1

SyntaxError: ignored

In [ ]:
1+ \
1

2

<div class="alert alert-block alert-info">
<b>Tip:</b> If you forgot a particular usage/structure/syntax, Google it or look for the help documents
</div>

In [ ]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __l

Or even simpler: execute with a "?"

In [ ]:
list?

## II. Core python language

(Python official tutorial: https://docs.python.org/3/tutorial/)

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic <b> quicksort </b> algorithm in Python. You might be impressed by its high readability:

```python
def quicksort(numlist): # numlist is a list of unsorted numbers to be sorted
    if len(numlist) <= 1:
        return numlist # If length smaller than 1, arr is already sorted
    pivot = numlist[len(numlist) // 2] # // gives the ceiling integer. 11//2=5
    left = [x for x in numlist if x < pivot] # like "for x in numlist, if x<pivot, collect x into a list 'left'"
    middle = [x for x in numlist if x == pivot]
    right = [x for x in numlist if x > pivot]
    return quicksort(left) + middle + quicksort(right) # recursively sort

print(quicksort([3,6,8,10,1,2,1]))
# Prints "[1, 1, 2, 3, 6, 8, 10]"
```

<div class="alert alert-block alert-info">
<b>Tip:</b> Here `quicksort()` is a function, `numlist` is a list of numbers provided when invoking this function. Functions in python are defined in a similar way as in other languages.
</div>

By just reading it in the sense of reading English, we already can summarize the quicksort algorithm:

- For an unsorted array <i> arr </i>, choose the number currently at middle position as a reference "pivot"
- Use lists <i> left </i>, <i> middle </i> and <i> right </i> to collect numbers that are smaller than, equal to, and larger than pivot.
- Sort the original list into (left)+(middle)+(right) form.
- Apply above procedure to <i> left </i> and <i> right </i> recursively

The major contribution to the readability in the above example is the <b> list comprehension</b> technique. We will give more examples about this elegant technique later.

### Python versions

There are currently two different supported versions of Python, 2.7 and 3.x (currently 3.8). Little incompatibilities (such as the print function) exist between python 2 and 3. For this course we'll all use python 3.x.


Let's check the system version first

In [ ]:
import sys
sys.version

'3.8.16 (default, Dec  7 2022, 01:12:13) \n[GCC 7.5.0]'

### Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

<div class="alert alert-block alert-info">
<b>Tip:</b> Variables don't have to be declared before use.
</div>

<b>Numbers:</b> Integers and floats work as you would expect from other languages:

```python
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"
```

<b>Booleans</b>: Python implements all of the usual operators for Boolean logic, but uses <b>English words</b> rather than symbols (&&, || in Mathematica):

```python
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"
```

#### Operations

Close to matlab. `*` for product should be explicitly written. However things like `a:b:c` for creating arrays in MATLAB are not supported in python.

<div class="alert alert-block alert-warning">
<b>Warning:</b> No `a++ a--` are allowed
</div>

In [ ]:
x=1;
x++

SyntaxError: ignored

<div class="alert alert-block alert-info">
<b>Tip:</b> Use `**` for exponentials. `^` does a "bitwise exclusive or"
</div>

You'll be familiar with basic data types quickly after you read and write some sample codes.

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples. <b> Lists and NumPy arrays </b> are widely used in this course.

Dictionaries: `key` + `value` pairs. Will see an example later.

Sets: similar to lists but contain no identical elements. `{1,2,3}`

Tuples: also similar to lists and sets. Immutable. `(1,2,3)`

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

```python
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"
```

<div class="alert alert-block alert-info">
<b>Tip:</b> Python indices count from 0.
</div>

##### Slicing a list

We've just seen that we can use a square bracket to access an element of a list. In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

```python
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"
```

##### Loops

You can loop over the elements of a list like this:

```python
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.
```

<div class="alert alert-block alert-info">
<b>Tip:</b> Pay attention to the syntax of `for ... in`
</div>

An equivalent form is:

```python
animals = ['cat', 'dog', 'monkey']
for i in range(animals):
    print(animals[i])
# Prints "cat", "dog", "monkey", each on its own line.
```

I usually think this form is less intuitive.

##### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

```python
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]
```

You also see how to write a `for` loop here. You may already notice that there is no bracket for the content of for loop. Instead, python use indent to identify code blocks. Usually when you type in `for x in nums:` and hit return/enter it will automatically indent for you.

You can make this code simpler using a list comprehension:

```python
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]
```

List comprehensions can also contain conditions (will also see later in the big example):

```python
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"
```

### Functions

Python functions are defined using the def keyword. For example:

```python
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"
```

In [ ]:
def g(x):
  x = x+1
  return x**2

g(10)

121

You also learn how to write an `if-else` condition expression here. We can conveniently define functions with optional keyword arguments, like this:

```python
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"
```

In this function `hello`, if you don't provide a value to `loud` when you call the function, it will take default key value `loud=False`

### Classes

We're not going into details about it. Understanding and use of classes are not required for this course (again, this is not a programming course!) However, <b> classes is a very important idea in programming in python</b>, so here we are going to take a glance at classes through short examples.

Generally, Classes provide a means of bundling data and functionality together. Now we define a class of complex numbers:

In [ ]:
class Complex:
    def __init__(self, realpart, imagpart): # initialization when creating an instance of this class.
        #self is a pointer toward the instance and the namespace. It is called self because of convention rather than being a special character.
        self.r = realpart
        self.i = imagpart

The `__init__()` method is invoked automatically when you create an instance. See below.

In [ ]:
x = Complex(3.0, -4.5)
x.r, x.i

(3.0, -4.5)

### Methods (“Functions in Classes”)

Roughly speaking methods are "objects in classes" that "behaves like" functions. We'll see a lot of examples of methods when we introduce NumPy. A key difference between functions and classes is:
- functions can called only by its name; defined independently.
- Calling methods should invoke the corresponding class; dependent on the corresponding class.

Here is a simple example of methods:

In [ ]:
class Dog:

    def __init__(self, name):
        self.name = name
        self.tricks = []

    def add_trick(self, trick): # This is a method of the Dog class. It adds tricks to a Dog instance
        self.tricks.append(trick)

In [ ]:
d = Dog('Fido')
d.add_trick('roll over') # method should invoke the corresponding class

In [ ]:
d.name

'Fido'

In [ ]:
d.tricks

['roll over']

<div class="alert alert-block alert-info">
<b>Tip:</b> `append` is a method of `list`
</div>

## III. Packages installed here in Google Colab (numpy, scipy, and matplotlib)

Most packages we will use in class should be pre-installed by your Python package distributor.  If you find installing additional packages hard, please contact me or use the Google Colab version of Python. 

For our class, we will mostly use three different Python packages.

- NumPy: Deals with N-dimensional arrays. Easy import and export.
- SciPy: Scientific functions. Equation solves may be used in this course
- Matplotlib: Plot things similar to making plots in matlab.

We will talk about NumPy in some detail here. Matplotlib will be covered in separate sections below. SciPy library will be introduced in the future if we need specific equation solvers or some other functions.

### NumPy

Numpy makes processing of N-dimensional arrays more easily. Here only a small fraction of NumPy is covered. Please check out the NumPy documentation: https://docs.scipy.org/doc/numpy/reference/ or try more problems and Google more (I prefer the latter)

I guess not many people want to type "numpy" again and again, so usually people import `numpy` with an alias `np`. You can use any alias you like but always keeping commonly-used alias may help improve the readability of your codes.

In [ ]:
import numpy as np # import the "collection of function" numpy library, then use the functions

In [ ]:
l = [1, 2, 3]/4
l

TypeError: ignored

In [ ]:
a = np.array([1, 2.1, 4])/4
a

array([0.25 , 0.525, 1.   ])

<div class="alert alert-block alert-info">
<b>Tip:</b> A python library is like a "reference book". In real life you "use a chapter or a section of a book" to help you solve a problem. In python you "use a function from a library" to help you solve a problem.
</div>

For most of the time we are using NumPy to construct "lists" (numpy.ndarray), and do array math conveniently. We also use some function solves provided by NumPy (see later)

<b> Constructing lists </b>:
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```
or
```python
numpy.arange([start, ]stop, [step, ]dtype=None)
```
Examples:

In [ ]:
np.linspace(2.0, 3.0, num=6)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
type(np.linspace(2.0, 3.0, num=5))

numpy.ndarray

In [ ]:
type(np.arange(3))

numpy.ndarray

In [ ]:
list(np.arange(3,7))

[3, 4, 5, 6]

Above actions creates an numpy.ndarry, which can be easily converted to list by list( ) function. BTW, you can actually create a list without NumPy, using the `range(m,n)` function.

Range is a built-in python data type. It's type is "range"

In [ ]:
type(range(1))

range

It is useful for looping. Same for NumPy arrays.

In [ ]:
for i in range(0,10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


OK, you already found that `range(10)` is a sequence from 0 to 9. Generally, `range(m,n)` is from $m$ to $n-1$. Do to the same thing as `np.linspace(2.0, 3.0, num=5)`, we can do

In [ ]:
[2+x/4 for x in range(5)]

[2.0, 2.25, 2.5, 2.75, 3.0]

It is a list with the same elements.

<b> Array math </b>: Here are some math operations for arrays that can be done conviently. Also very easily readable. Please read through and have an idea of <b> what can NumPy do </b>. Memorizing syntax is not quite necessary since the references of usage are easily found online.

```python
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))
```

Note that unlike MATLAB (but just like Mathematica!), `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

```python
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
```

By the way, in Mathematica you have:
```Wolfram
In[1]:= {1, 2, 3} {4, 5, 6}
Out[1]:= {4,10,18}

In[2]:= Dot[{1, 2, 3},{4, 5, 6}]
Out[2]:= 32
```

Other functions such as sum of an array and transpose

```python
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
```

```python
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"
```

<div class="alert alert-block alert-info">
<b>Tip:</b> Dot and transposes are methods of arrays
</div>

There are many more functions provided by NumPy. Check them out on official documentation of NumPy. Things beyond list manipulation will almost surely not be required in coding for this course.

### SciPy

Numpy provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.


In this course, the major use of scipy is the various solvers which are easily identified in the official documentation. The detailed usage will be introduced when we move to related topics.